apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2016-06-15T18:38:26Z
  labels:
    app: camel-kubernetes-example
  name: camel-kubernetes-example
  namespace: spring-boot
  resourceVersion: "14078"
  selfLink: /oapi/v1/namespaces/spring-boot/deploymentconfigs/camel-kubernetes-example
  uid: 591c79ac-3328-11e6-aa37-5254006622ac
spec:
  replicas: 1
  selector:
    app: camel-kubernetes-example
    deploymentconfig: camel-kubernetes-example
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: camel-kubernetes-example
        deploymentconfig: camel-kubernetes-example
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: 172.30.125.205:5000/spring-boot/camel-kubernetes-example@sha256:dd56c10b54be10dd8642dd80dc5deadf67b94ce298bf104469ca461b8a629870
        imagePullPolicy: Always
        name: camel-kubernetes-example
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - camel-kubernetes-example
      from:
        kind: ImageStreamTag
        name: camel-kubernetes-example:latest
      lastTriggeredImage: 172.30.125.205:5000/spring-boot/camel-kubernetes-example@sha256:dd56c10b54be10dd8642dd80dc5deadf67b94ce298bf104469ca461b8a629870
    type: ImageChange
status:
  details:
    causes:
    - imageTrigger:
        from: {}
      type: ImageChange
  latestVersion: 6